baseURL = "www.example.com"
languageCode = "en-us"
title = "Ghostie Producer"
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 3
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Services"
url = "/services/"
weight = 2
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.footer]
copyright_text = "Ghostie Producer 2021"
[params.homepage]
hide_view_all_services = false
show_call_box = true
[params.homepage_meta_tags]
meta_description = "Ghostie is a music producer London based."
meta_og_description = "Ghostie is a music producer London based."
meta_og_image = "https://i.ibb.co/NsKSDXf/ghostie.jpg"
meta_og_title = "Ghostie Producer"
meta_og_type = "website"
meta_og_url = "https://ghostieprod.netlify.app"
meta_twitter_card = "summary"
meta_twitter_creator = "@ghostieprod"
meta_twitter_site = "@ghostieprod"
[params.logo]
alt = "Ghostie Producer"
desktop = "https://i.ibb.co/NsKSDXf/ghostie.jpg"
desktop_height = "36px"
mobile = "https://i.ibb.co/NsKSDXf/ghostie.jpg"
[params.team]
summary_large_truncate = 120
