baseURL = "www.example.com"
languageCode = "en-us"
title = "Hugo Serif Theme"
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 3
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Services"
url = "/services/"
weight = 2
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.footer]
copyright_text = "Ghostie Producer 2021"
[params.homepage]
hide_view_all_services = false
show_call_box = true
[params.homepage_meta_tags]
meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
meta_og_title = "Ghostie Producer"
meta_og_type = "website"
meta_og_url = "https://ghostieprod.netlify.app"
meta_twitter_card = "summary"
meta_twitter_creator = "@ghostieprod"
meta_twitter_site = "@ghostieprod"
[params.logo]
alt = "Ghostie Producer"
desktop = "images/logo/logo.svg"
desktop_height = "36px"
mobile = "images/logo/logo-mobile.svg"
[params.team]
summary_large_truncate = 120
